import type { Task } from "@/types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Thiết kế giao diện Dashboard",
    description: "Tạo wireframe và mockup cho trang Dashboard chính",
    status: "done",
    priority: "high",
    assignee: "Nguyễn Văn A",
    dueDate: "2025-12-20",
    createdAt: "2025-11-01T08:00:00Z",
    tags: ["UI/UX", "design"],
  },
  {
    id: "2",
    title: "Xây dựng API đăng nhập",
    description: "Implement JWT authentication cho hệ thống",
    status: "done",
    priority: "high",
    assignee: "Trần Văn B",
    dueDate: "2025-12-15",
    createdAt: "2025-11-02T09:00:00Z",
    tags: ["backend", "auth"],
  },
  {
    id: "3",
    title: "Tích hợp Redux Toolkit",
    description: "Setup store, slices và typed hooks cho state management",
    status: "done",
    priority: "medium",
    assignee: "Lê Thị C",
    dueDate: "2025-12-18",
    createdAt: "2025-11-03T10:00:00Z",
    tags: ["frontend", "state"],
  },
  {
    id: "4",
    title: "Viết unit test cho selectors",
    description: "Test tất cả memoized selectors trong tasksSlice",
    status: "in_progress",
    priority: "medium",
    assignee: "Phạm Văn D",
    dueDate: "2025-12-25",
    createdAt: "2025-11-04T11:00:00Z",
    tags: ["testing"],
  },
  {
    id: "5",
    title: "Responsive layout cho mobile",
    description: "Đảm bảo giao diện hoạt động tốt trên thiết bị di động",
    status: "in_progress",
    priority: "high",
    assignee: "Nguyễn Văn A",
    dueDate: "2025-12-28",
    createdAt: "2025-11-05T08:30:00Z",
    tags: ["UI/UX", "responsive"],
  },
  {
    id: "6",
    title: "Optimize bundle size",
    description: "Phân tích và tối ưu kích thước build production",
    status: "todo",
    priority: "low",
    assignee: "Trần Văn B",
    dueDate: "2026-01-05",
    createdAt: "2025-11-06T09:30:00Z",
    tags: ["performance"],
  },
  {
    id: "7",
    title: "Thiết kế dark mode",
    description: "Implement dark mode toggle với Ant Design ConfigProvider",
    status: "done",
    priority: "medium",
    assignee: "Lê Thị C",
    dueDate: "2025-12-22",
    createdAt: "2025-11-07T10:30:00Z",
    tags: ["UI/UX", "theme"],
  },
  {
    id: "8",
    title: "Tạo component TaskFormModal",
    description: "Form thêm/sửa task với Ant Design Form validation",
    status: "done",
    priority: "high",
    assignee: "Phạm Văn D",
    dueDate: "2025-12-19",
    createdAt: "2025-11-08T11:30:00Z",
    tags: ["frontend", "form"],
  },
  {
    id: "9",
    title: "Implement bulk delete",
    description: "Cho phép chọn nhiều task và xoá hàng loạt",
    status: "in_progress",
    priority: "medium",
    assignee: "Nguyễn Văn A",
    dueDate: "2025-12-30",
    createdAt: "2025-11-09T08:00:00Z",
    tags: ["feature"],
  },
  {
    id: "10",
    title: "Setup CI/CD pipeline",
    description: "Cấu hình GitHub Actions cho auto deploy",
    status: "todo",
    priority: "low",
    assignee: "Trần Văn B",
    dueDate: "2026-01-10",
    createdAt: "2025-11-10T09:00:00Z",
    tags: ["devops"],
  },
  {
    id: "11",
    title: "Tích hợp ESLint + Prettier",
    description: "Đảm bảo code consistency trong toàn bộ dự án",
    status: "done",
    priority: "low",
    assignee: "Lê Thị C",
    dueDate: "2025-12-10",
    createdAt: "2025-11-11T10:00:00Z",
    tags: ["tooling"],
  },
  {
    id: "12",
    title: "Xây dựng filter bar component",
    description: "Search, filter theo status/priority, date range picker",
    status: "done",
    priority: "high",
    assignee: "Phạm Văn D",
    dueDate: "2025-12-21",
    createdAt: "2025-11-12T11:00:00Z",
    tags: ["frontend", "filter"],
  },
  {
    id: "13",
    title: "Viết documentation",
    description: "README.md với hướng dẫn cài đặt, chạy và sử dụng",
    status: "in_progress",
    priority: "medium",
    assignee: "Nguyễn Văn A",
    dueDate: "2026-01-02",
    createdAt: "2025-11-13T08:30:00Z",
    tags: ["docs"],
  },
  {
    id: "14",
    title: "Thêm animation cho cards",
    description: "Micro-animations khi hover và transition giữa các trang",
    status: "todo",
    priority: "low",
    assignee: "Trần Văn B",
    dueDate: "2026-01-08",
    createdAt: "2025-11-14T09:30:00Z",
    tags: ["UI/UX", "animation"],
  },
  {
    id: "15",
    title: "Internationalization (i18n)",
    description: "Hỗ trợ đa ngôn ngữ Việt/Anh cho ứng dụng",
    status: "todo",
    priority: "low",
    assignee: "Lê Thị C",
    dueDate: "2026-01-15",
    createdAt: "2025-11-15T10:30:00Z",
    tags: ["i18n"],
  },
  {
    id: "16",
    title: "Implement drag & drop",
    description: "Cho phép kéo thả task giữa các cột trạng thái",
    status: "todo",
    priority: "medium",
    assignee: "Phạm Văn D",
    dueDate: "2026-01-12",
    createdAt: "2025-11-16T11:30:00Z",
    tags: ["feature", "UX"],
  },
  {
    id: "17",
    title: "Tối ưu SEO cho SPA",
    description: "Meta tags, title, Open Graph cho các trang chính",
    status: "todo",
    priority: "low",
    dueDate: "2026-01-20",
    createdAt: "2025-11-17T08:00:00Z",
    tags: ["SEO"],
  },
  {
    id: "18",
    title: "Error boundary component",
    description: "Xử lý lỗi gracefully với React Error Boundary",
    status: "in_progress",
    priority: "high",
    assignee: "Nguyễn Văn A",
    dueDate: "2025-12-27",
    createdAt: "2025-11-18T09:00:00Z",
    tags: ["frontend", "error-handling"],
  },
  {
    id: "19",
    title: "Performance monitoring",
    description: "Tích hợp React DevTools profiler và Web Vitals",
    status: "todo",
    priority: "low",
    assignee: "Trần Văn B",
    dueDate: "2026-01-18",
    createdAt: "2025-11-19T10:00:00Z",
    tags: ["performance", "monitoring"],
  },
  {
    id: "20",
    title: "Security audit",
    description: "Rà soát XSS, CSRF và các lỗ hổng bảo mật phổ biến",
    status: "todo",
    priority: "high",
    assignee: "Lê Thị C",
    dueDate: "2026-05-26",
    createdAt: "2025-11-20T11:00:00Z",
    tags: ["security", "audit"],
  },
  {
    id: "21",
    title: "Cập nhật tài liệu hướng dẫn",
    description: "Bổ sung hướng dẫn sử dụng các tính năng mới cho end-user",
    status: "todo",
    priority: "high",
    assignee: "Lê Thị D",
    dueDate: "2026-02-26",
    createdAt: "2025-11-20T11:00:00Z",
    tags: ["docs", "guide"],
  },
];
